AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Secret manager resources

Parameters:
  Env:
    Type: String
    Default: dev

Resources:

  Secrets:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Secret keys (etc)
      Name: Secrets
      SecretString: '{"jwtPrivateKey":"-"}'

Outputs:
  Secrets:
    Description: SaaS secrets arn
    Value: !Ref Secrets